# Generated by Django 4.0 on 2022-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('host', models.CharField(max_length=8, unique=True)),
                ('guest_pause', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default='1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
